### PR TITLE
Tachiyomi to Paperback Backup Converter

### PR DESCRIPTION
**Pull request by FramboisePi**
This pull request add a Tachiyomi to Paperback Backup Converter page to the website.

The page use a Vue component `BackupConverter` which allow the user to upload a backup file and download the converted backup. 
The conversion is done by Vibrant tool: [Tachiyomi to Paperback Backup Converter](https://github.com/Paperback-iOS/Tachiyomi-To-Paperbackup-Converter).

### Website side of the tool proccess
`BackupConverter` component renders an upload component.
When the user add a file, the method `sendRequest` is called. This method send a POST request to the conversion server which return a converted backup which is displayed in a dialog windows. If an error occur, an alert is shown with the error content.

---

The tool is available here: https://deploy-preview-65--paperbackios.netlify.app/tools/backup-converter/

### TODO
 * [x] Put the tool in a better place. `/tools/backup-converter`?
 * [x] Fix dark mode style
 * [ ] Remove extra logging and open dialog button
 * [x] Improve small screen layout
 * [x] Make the download button work on an iOS device
 * [x] Insert the backup in the downloaded file...

### Potential issue
Timeout should not happen as the converter tool was modified to return an error when given an incompatible file.
A timeout lead to the error `Uncaught (in promise) TypeError: can't access property "data", error.response is undefined`

### CODE REVIEW

**Review by ConradWeiser — DISMISSED** [review]
From the demos that I've seen of this running, I don't have any issue of it being pushed as-is.
I suggest a tab at the top with a dropdown called 'Tools' or something to bring you to the page!

**Comment by FramboisePi** [comment]
Thanks Vibrant. The Tool menu was added in 7cd1698. 
We are still experimenting with the table and the dark theme. After that, it will be ready!

**Comment by FramboisePi** [comment]
The tool should now work on iOS and iPadOS. This pull request should be ready for review.

**Review by ConradWeiser — APPROVED** [review]
I think this is set to go as-is!
I've toyed around with it on the demo link for a while and don't see any issues!

**Pull request merged**
